name: fastai-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - fastai
  - jupyter
  - matplotlib
  - pandas
  - numpy
  - pillow
  - pip:
    - datasets